/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jarvis_tbaseview_jni_JniHelloWorld */

#ifndef _Included_com_jarvis_tbaseview_jni_JniHelloWorld
#define _Included_com_jarvis_tbaseview_jni_JniHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jarvis_tbaseview_jni_JniHelloWorld
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jarvis_tbaseview_jni_JniHelloWorld_square
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jarvis_tbaseview_jni_JniHelloWorld
 * Method:    setSay
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jarvis_tbaseview_jni_JniHelloWorld_setSay
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
